<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ASDW0041" name="com.qait.acs.tests.TestFirst" tests="10" failures="5" timestamp="30 Jul 2018 13:15:36 GMT" time="558.098" errors="0">
  <testcase name="testingservicesmenu" time="23.365" classname="com.qait.acs.tests.TestFirst"/>
  <testcase name="checkingteam" time="97.661" classname="com.qait.acs.tests.TestFirst">
    <failure type="java.lang.AssertionError" message="FAILED: Element &#039;team_text&#039; not found on the QainfotechHomePage !!!">
      <![CDATA[java.lang.AssertionError: FAILED: Element 'team_text' not found on the QainfotechHomePage !!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:87)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:65)
	at com.qait.acs.keywords.QainfotechHomePage.checkteammenu(QainfotechHomePage.java:63)
	at com.qait.acs.tests.TestFirst.checkingteam(TestFirst.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkingteam -->
  <testcase name="verify_in_search_functionality" time="24.893" classname="com.qait.acs.tests.TestFirst"/>
  <testcase name="testingcontact" time="90.021" classname="com.qait.acs.tests.TestFirst">
    <failure type="java.lang.AssertionError" message="FAILED: Element &#039;contact&#039; not found on the QainfotechHomePage !!!">
      <![CDATA[java.lang.AssertionError: FAILED: Element 'contact' not found on the QainfotechHomePage !!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:87)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:65)
	at com.qait.acs.keywords.QainfotechHomePage.check_contact_menu(QainfotechHomePage.java:75)
	at com.qait.acs.tests.TestFirst.testingcontact(TestFirst.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testingcontact -->
  <testcase name="verify_vertical_ssection" time="90.042" classname="com.qait.acs.tests.TestFirst">
    <failure type="java.lang.AssertionError" message="FAILED: Element &#039;vertical&#039; not found on the QainfotechHomePage !!!">
      <![CDATA[java.lang.AssertionError: FAILED: Element 'vertical' not found on the QainfotechHomePage !!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:87)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:65)
	at com.qait.acs.keywords.QainfotechHomePage.clickonhealthcares(QainfotechHomePage.java:80)
	at com.qait.acs.tests.TestFirst.verify_vertical_ssection(TestFirst.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_vertical_ssection -->
  <testcase name="Step01_Launch_Application" time="7.330" classname="com.qait.acs.tests.TestFirst"/>
  <testcase name="testing_news" time="22.465" classname="com.qait.acs.tests.TestFirst"/>
  <testcase name="testinginnovation" time="22.212" classname="com.qait.acs.tests.TestFirst"/>
  <testcase name="verify_download_section" time="90.039" classname="com.qait.acs.tests.TestFirst">
    <failure type="java.lang.AssertionError" message="FAILED: Element &#039;knowledgecenter&#039; not found on the QainfotechHomePage !!!">
      <![CDATA[java.lang.AssertionError: FAILED: Element 'knowledgecenter' not found on the QainfotechHomePage !!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:87)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:65)
	at com.qait.acs.keywords.QainfotechHomePage.clickdownloadsection(QainfotechHomePage.java:93)
	at com.qait.acs.tests.TestFirst.verify_download_section(TestFirst.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_download_section -->
  <testcase name="testingvertical" time="90.070" classname="com.qait.acs.tests.TestFirst">
    <failure type="java.lang.AssertionError" message="FAILED: Element &#039;vertical&#039; not found on the QainfotechHomePage !!!">
      <![CDATA[java.lang.AssertionError: FAILED: Element 'vertical' not found on the QainfotechHomePage !!!
	at org.testng.Assert.fail(Assert.java:94)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:87)
	at com.qait.automation.getpageobjects.GetPage.element(GetPage.java:65)
	at com.qait.acs.keywords.QainfotechHomePage.checkverticalmenu(QainfotechHomePage.java:47)
	at com.qait.acs.tests.TestFirst.testingvertical(TestFirst.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testingvertical -->
</testsuite> <!-- com.qait.acs.tests.TestFirst -->
